apiVersion: v1
# 리소스 객체 종류가 Secret이다. 
kind: Secret
# 시크릿 리소스의 메타정보 
metadata:
  # 시크릿 이름 
  name: mysecret
  # 네임스페이시 위치
  namespace: default
# 시크릿 타입 
type: Opaque
# 시크릿에 저장될 데이터 (시크릿 값은 base64로 인코딩된다.)
data:
  # Example:
  # password: {{ .Values.password | b64enc }}