apiVersion: batch/v1beta1
# 리소스 타입이 CronJob임을 알린다. 
kind: CronJob
# 메타정보: 이름, 설치될 네임스페이스 
metadata:
  name: hello
  namespace: default
# 스펙 설정 영역 
spec:
  # 리눅스 cron의 형식과 동일하게 스케줄을 걸어준다. 분,시,일,주,월
  schedule: "*/1 * * * *"
  # Job으로 수행할 템플릿 정보를 지정한다. 
  jobTemplate:
    spec:
      template:
        # 컨테이너를 위한 스펙 설정 
        spec:
          # 컨테이너 설정 
          containers:
          # 컨테이너 이름 
          - name: hello
            # 이미지 
            image: busybox
            # 배치가 수행될때 args 를 통해서 커맨드가 수행된다. 
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
          # 재시작 정책 (OnFailure는 실패시에만 재시작하도록 한다. )
          # Always: 항상 재시작 한다. 
          # OnFailure: 실패시에만 재시작한다. 
          # Never: 재시작을 하지 않는다. 
          restartPolicy: OnFailure